// Generated by SecuredMe Education adapter scaffold.
"use strict";

const vscode = require("vscode");

function activate(context) {
  const disposable = vscode.commands.registerCommand("securedme.votguardian.openAdapter", function () {
    vscode.window.showInformationMessage("V.O.T Guardian Antigravity adapter is installed locally. WebAuth uses browser-first flow; no secrets are read.");
  });
  context.subscriptions.push(disposable);
}

function deactivate() {}

module.exports = {
  activate,
  deactivate,
};
